// Enigma Astrology Research.
// Jan Kampherbeek, (c) 2023.
// All Enigma software is open source.
// Please check the file copyright.txt in the root of the source for further details.


using Enigma.Domain.References;
using LiteDB;

namespace Enigma.Domain.Persistables;

/// <summary>Representation of chartdata to be saved in Json format</summary>
/// <remarks>The format is flat to simplify the corresponding Json structure.</remarks>
public class PersistableChartData
{
    /// <summary>Unique id for the chart, primary key, generated by LiteDB.</summary>
    public int Id { get; }
    /// <summary>Name or other identification for the chart.</summary>
    /// <remarks>Should be unique within the database.</remarks>
    public string Name { get; }
    /// <summary>Optional description of the chart.</summary>
    public string Description { get; }
    /// <summary>Optional description of the source of the chart data.</summary>
    public string Source { get; }
    /// <summary>Optional cartegory of the chart.</summary>
    /// <remarks>If not used defaults to ChartCategories.Unknown.</remarks>
    public ChartCategories ChartCategory { get; }
    /// <summary>Optional rating of the quality of the source according to Louise Rodden.</summary>
    /// <remarks>If not used defaults to RoddenRatings.Unknown.</remarks>
    public RoddenRatings Rating { get; }
    /// <summary>Julian day number for ephemeris time.</summary>
    public double JulianDayEt { get; }
    /// <summary>Data as text.</summary>
    /// <remarks>Only for presentational purposes.</remarks>
    public string DateText { get; }
    /// <summary>Time as text.</summary>
    /// <remarks>Only for presentational purposes.</remarks>
    public string TimeText { get; }
    /// <summary>Locationname.</summary>
    /// <remarks>Only for presentational purposes.</remarks>
    public string LocationName { get; }
    /// <summary>Geographic longitude (east = +, west = -.</summary>
    public double GeoLong { get; }
    /// <summary>Geographic latitude (north = +, south = -).</summary>
    public double GeoLat { get; }


    [BsonCtor]
    public PersistableChartData(string name, string description, string source, ChartCategories chartCategory, 
        RoddenRatings rating, double julianDayEt, string dateText, string timeText, string locationName, 
        double geoLong, double geoLat, int id = 0)
    {
        Id = id;
        Name = name;
        Description = description;
        Source = source;
        ChartCategory = chartCategory;
        Rating = rating;
        JulianDayEt = julianDayEt;
        DateText = dateText;
        TimeText = timeText;
        LocationName = locationName;
        GeoLong = geoLong;
        GeoLat = geoLat;
    }


}