// Enigma Astrology Research.
// Jan Kampherbeek, (c) 2023.
// All Enigma software is open source.
// Please check the file copyright.txt in the root of the source for further details.

namespace Enigma.Domain.Persistency;

/// <summary>Intersection data between charts and events.</summary>
public sealed class InterChartEvent
{
    /// <summary>Unique id for the intersection, primary key, generated by LiteDB.</summary>
    public int Id { get; set; }
    /// <summary>Primary key for chart. </summary>
    public int ChartId { get; }
    /// <summary>Primary key for event. </summary>
    public int EventId { get; }

    public InterChartEvent(int chartId, int eventId)
    {
        ChartId = chartId;
        EventId = eventId;
    }

}
