namespace Enigma.Domain.Persistency;

/// <summary>Intersection between charts and periods.</summary>
public sealed class InterChartPeriod
{
    /// <summary>Unique id for the intersection, primary key, generated by LiteDB.</summary>
    public int Id { get; set; }
    /// <summary>Primary key for chart. </summary>
    public int ChartId { get; }
    /// <summary>Primary key for period. </summary>
    public int PeriodId { get; }

    public InterChartPeriod(int chartId, int periodId)
    {
        ChartId = chartId;
        PeriodId = periodId;
    }
}
